"""SentinelAPI PDF Report Generation Engine.

Generates two beautifully formatted, professional executive PDF reports:
  1. vulnerabilities.pdf — Detailed findings, risk scoring, PoC curl commands, and remediation blueprints.
  2. all_logs.pdf — Complete execution telemetry, probe success/failure breakdown, HTTP codes, and latency logs.
"""
from pathlib import Path
from typing import List, Dict, Any, Optional
import time
import hashlib
import html

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
    KeepTogether,
    HRFlowable,
)
from reportlab.pdfgen import canvas

from sentinelapi.core.models import MasterScanResult, ScanResult, Finding, ProbeError, ScanStatus


def _esc(val: Any) -> str:
    """Escapes strings for ReportLab XML paragraph tags safely."""
    if val is None:
        return ""
    return html.escape(str(val))


# ───────────────────────────────────────────────────────────
# Two-Pass Numbered Canvas for "Page X of Y" + Running Header
# ───────────────────────────────────────────────────────────
class NumberedCanvas(canvas.Canvas):
    """Adds running headers and footers with accurate total page counts."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count: int):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748b"))

        # Running Header (pages > 1)
        if self._pageNumber > 1:
            self.drawString(54, 750, "SENTINELAPI SECURITY ASSESSMENT REPORT")
            self.drawRightString(558, 750, "CONFIDENTIAL & PROPRIETARY")
            self.setStrokeColor(colors.HexColor("#e2e8f0"))
            self.setLineWidth(0.5)
            self.line(54, 742, 558, 742)

        # Running Footer (all pages)
        self.setStrokeColor(colors.HexColor("#e2e8f0"))
        self.setLineWidth(0.5)
        self.line(54, 45, 558, 45)

        self.drawString(54, 32, "Generated by SentinelAPI Core Security Engine • Automated CI/CD Report")
        self.drawRightString(558, 32, f"Page {self._pageNumber} of {page_count}")
        self.restoreState()


# ───────────────────────────────────────────────────────────
# Style Palette Helper
# ───────────────────────────────────────────────────────────
def _get_pdf_styles():
    base = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "DocTitle",
        parent=base["Normal"],
        fontName="Helvetica-Bold",
        fontSize=22,
        leading=26,
        textColor=colors.HexColor("#0f172a"),
        spaceAfter=4,
    )

    subtitle_style = ParagraphStyle(
        "DocSubtitle",
        parent=base["Normal"],
        fontName="Helvetica",
        fontSize=10,
        leading=14,
        textColor=colors.HexColor("#64748b"),
        spaceAfter=14,
    )

    h1_style = ParagraphStyle(
        "Heading1_Custom",
        parent=base["Normal"],
        fontName="Helvetica-Bold",
        fontSize=13,
        leading=17,
        textColor=colors.HexColor("#0f172a"),
        spaceBefore=14,
        spaceAfter=8,
    )

    body_style = ParagraphStyle(
        "Body_Custom",
        parent=base["Normal"],
        fontName="Helvetica",
        fontSize=9,
        leading=13,
        textColor=colors.HexColor("#334155"),
    )

    code_style = ParagraphStyle(
        "Code_Custom",
        parent=base["Normal"],
        fontName="Courier",
        fontSize=7.5,
        leading=10,
        textColor=colors.HexColor("#0f172a"),
    )

    bold_cell = ParagraphStyle(
        "BoldCell",
        parent=base["Normal"],
        fontName="Helvetica-Bold",
        fontSize=8.5,
        leading=11,
        textColor=colors.HexColor("#0f172a"),
    )

    table_cell = ParagraphStyle(
        "TableCell",
        parent=base["Normal"],
        fontName="Helvetica",
        fontSize=8,
        leading=11,
        textColor=colors.HexColor("#334155"),
    )

    h2_style = ParagraphStyle(
        "Heading2_Custom",
        parent=base["Normal"],
        fontName="Helvetica-Bold",
        fontSize=10.5,
        leading=14,
        textColor=colors.HexColor("#0f172a"),
        spaceBefore=10,
        spaceAfter=5,
    )

    mono_cell = ParagraphStyle(
        "MonoCell",
        parent=base["Normal"],
        fontName="Courier",
        fontSize=7,
        leading=9.5,
        textColor=colors.HexColor("#0f172a"),
    )

    diag_cell = ParagraphStyle(
        "DiagCell",
        parent=base["Normal"],
        fontName="Helvetica",
        fontSize=7.5,
        leading=10,
        textColor=colors.HexColor("#334155"),
    )

    small_body = ParagraphStyle(
        "SmallBody",
        parent=base["Normal"],
        fontName="Helvetica",
        fontSize=7.5,
        leading=10.5,
        textColor=colors.HexColor("#475569"),
    )

    return {
        "title": title_style,
        "subtitle": subtitle_style,
        "h1": h1_style,
        "h2": h2_style,
        "body": body_style,
        "small_body": small_body,
        "code": code_style,
        "bold_cell": bold_cell,
        "table_cell": table_cell,
        "mono_cell": mono_cell,
        "diag_cell": diag_cell,
    }


def _status_color(status: str) -> colors.Color:
    if status == "PASS":
        return colors.HexColor("#059669")
    elif status == "FAIL":
        return colors.HexColor("#dc2626")
    elif status == "ERROR":
        return colors.HexColor("#b91c1c")
    elif status == "INCOMPLETE":
        return colors.HexColor("#d97706")
    return colors.HexColor("#475569")


def _severity_color(sev: str) -> colors.Color:
    s = (sev or "").upper()
    if s == "CRITICAL":
        return colors.HexColor("#991b1b")
    elif s == "HIGH":
        return colors.HexColor("#dc2626")
    elif s == "MEDIUM":
        return colors.HexColor("#d97706")
    elif s == "LOW":
        return colors.HexColor("#2563eb")
    return colors.HexColor("#059669")


# ───────────────────────────────────────────────────────────
# 1. Generate vulnerabilities.pdf
# ───────────────────────────────────────────────────────────
def generate_vulnerabilities_pdf(master_result: MasterScanResult, output_path: Path) -> Path:
    """Generates an executive, publication-grade vulnerability audit report PDF."""
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=54,
        bottomMargin=54,
    )

    styles = _get_pdf_styles()
    story = []

    # ── Title Banner ──
    story.append(Paragraph("SENTINELAPI VULNERABILITY AUDIT REPORT", styles["title"]))
    timestamp_str = master_result.end_time or time.strftime("%Y-%m-%d %H:%M:%S UTC")
    story.append(Paragraph(f"OWASP API Security Top 10 Assessment • Generated: {timestamp_str}", styles["subtitle"]))

    # ── Executive Metadata Card ──
    status_text = master_result.status
    st_col = _status_color(status_text)

    meta_data = [
        [
            Paragraph("<b>Target API:</b>", styles["body"]),
            Paragraph(f"<b>{master_result.target_title}</b>", styles["body"]),
            Paragraph("<b>Audit Status:</b>", styles["body"]),
            Paragraph(f"<font color='{st_col.hexval()}'><b>{status_text} (Exit Code: {master_result.exit_code})</b></font>", styles["body"]),
        ],
        [
            Paragraph("<b>Base URL:</b>", styles["body"]),
            Paragraph(f"<code>{master_result.base_url}</code>", styles["body"]),
            Paragraph("<b>Auth Scheme:</b>", styles["body"]),
            Paragraph(master_result.auth_scheme or "None / Public", styles["body"]),
        ],
        [
            Paragraph("<b>Probe Coverage:</b>", styles["body"]),
            Paragraph(f"{master_result.total_successful_probes} / {master_result.total_planned_probes} ({master_result.total_failed_probes} failed)", styles["body"]),
            Paragraph("<b>Endpoints:</b>", styles["body"]),
            Paragraph(str(master_result.total_endpoints), styles["body"]),
        ],
    ]
    meta_table = Table(meta_data, colWidths=[90, 180, 90, 144])
    meta_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
            ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#cbd5e1")),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ])
    )
    story.append(meta_table)
    story.append(Spacer(1, 14))

    # ── Executive Severity Counter Cards ──
    vulns = master_result.all_vulnerable_findings
    stats_data = [
        [
            Paragraph("<b>Total Findings</b>", styles["table_cell"]),
            Paragraph("<b>Critical</b>", styles["table_cell"]),
            Paragraph("<b>High</b>", styles["table_cell"]),
            Paragraph("<b>Medium</b>", styles["table_cell"]),
            Paragraph("<b>Low</b>", styles["table_cell"]),
        ],
        [
            Paragraph(f"<font size=14 color='#dc2626'><b>{len(vulns)}</b></font>", styles["body"]),
            Paragraph(f"<font size=14 color='#991b1b'><b>{master_result.total_critical}</b></font>", styles["body"]),
            Paragraph(f"<font size=14 color='#dc2626'><b>{master_result.total_high}</b></font>", styles["body"]),
            Paragraph(f"<font size=14 color='#d97706'><b>{master_result.total_medium}</b></font>", styles["body"]),
            Paragraph(f"<font size=14 color='#2563eb'><b>{master_result.total_low}</b></font>", styles["body"]),
        ],
    ]
    stats_table = Table(stats_data, colWidths=[100, 100, 100, 102, 102])
    stats_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f172a")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("BACKGROUND", (0, 1), (-1, 1), colors.HexColor("#f1f5f9")),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#cbd5e1")),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ])
    )
    story.append(stats_table)
    story.append(Spacer(1, 16))

    # ── OWASP Module Results Matrix ──
    story.append(Paragraph("OWASP API Security Top 10 Assessment Matrix", styles["h1"]))

    module_rows = [
        [
            Paragraph("<b>#</b>", styles["bold_cell"]),
            Paragraph("<b>Security Module</b>", styles["bold_cell"]),
            Paragraph("<b>OWASP</b>", styles["bold_cell"]),
            Paragraph("<b>Probes</b>", styles["bold_cell"]),
            Paragraph("<b>Vulns</b>", styles["bold_cell"]),
            Paragraph("<b>Status</b>", styles["bold_cell"]),
        ]
    ]

    for idx, (mod_id, mod_res) in enumerate(master_result.module_results.items(), 1):
        st = mod_res.status
        col = _status_color(st)
        vuln_cnt = len(mod_res.vulnerable_findings)
        vuln_text = f"<font color='#dc2626'><b>{vuln_cnt}</b></font>" if vuln_cnt > 0 else "<font color='#059669'>0</font>"

        module_rows.append([
            Paragraph(str(idx), styles["table_cell"]),
            Paragraph(mod_res.scanner_name, styles["bold_cell"]),
            Paragraph(mod_res.owasp_category, styles["table_cell"]),
            Paragraph(f"{mod_res.successful_probes}/{mod_res.planned_probes}", styles["table_cell"]),
            Paragraph(vuln_text, styles["table_cell"]),
            Paragraph(f"<font color='{col.hexval()}'><b>{st}</b></font>", styles["bold_cell"]),
        ])

    mod_table = Table(module_rows, colWidths=[24, 180, 80, 70, 60, 90])
    mod_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e293b")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#cbd5e1")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("ALIGN", (0, 0), (0, -1), "CENTER"),
            ("ALIGN", (3, 0), (-1, -1), "CENTER"),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ])
    )
    story.append(mod_table)
    story.append(Spacer(1, 16))

    # ── Detailed Vulnerability Findings & Remediation ──
    story.append(Paragraph(f"Detailed Vulnerability Findings ({len(vulns)} Confirmed)", styles["h1"]))

    if not vulns:
        cleared_panel = Table(
            [[Paragraph("<font size=11 color='#059669'><b>✔ SECURITY CLEARANCE: ZERO VULNERABILITIES IDENTIFIED</b><br/>All evaluated endpoints passed zero-trust boundary verification, strict access control checks, and rate limit validation.</font>", styles["body"])]],
            colWidths=[504]
        )
        cleared_panel.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#ecfdf5")),
            ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#059669")),
            ("PADDING", (0, 0), (-1, -1), 12),
        ]))
        story.append(cleared_panel)
    else:
        for idx, f in enumerate(vulns, 1):
            sev_col = _severity_color(f.severity)

            header_text = f"<b>Finding #{idx}: [{f.severity}] {f.title}</b>"
            details = [
                [
                    Paragraph(f"<b>Endpoint:</b> <code>{f.method} {f.endpoint}</code>", styles["table_cell"]),
                    Paragraph(f"<b>OWASP:</b> {f.owasp_category}", styles["table_cell"]),
                ],
                [
                    Paragraph(f"<b>CWE:</b> {f.cwe or 'CWE-Unknown'}", styles["table_cell"]),
                    Paragraph(f"<b>HTTP Status:</b> {f.status_code or 'N/A'}", styles["table_cell"]),
                ],
            ]

            card_content = [
                Paragraph(header_text, ParagraphStyle("Hdr", parent=styles["bold_cell"], textColor=sev_col, fontSize=10)),
                Spacer(1, 4),
                Table(details, colWidths=[250, 240]),
                Spacer(1, 4),
                Paragraph(f"<b>Evidence / Impact:</b> {f.evidence or f.description}", styles["body"]),
            ]

            if f.reproduction_curl:
                card_content.extend([
                    Spacer(1, 4),
                    Paragraph("<b>Proof of Concept (cURL):</b>", styles["bold_cell"]),
                    Paragraph(f"<code>{f.reproduction_curl}</code>", styles["code"]),
                ])

            if f.remediation:
                card_content.extend([
                    Spacer(1, 4),
                    Paragraph(f"<b>Remediation Blueprint:</b> {f.remediation}", styles["body"]),
                ])

            # Wrap each finding in a styled box
            finding_box = Table([[card_content]], colWidths=[504])
            finding_box.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#ffffff")),
                ("BOX", (0, 0), (-1, -1), 1, sev_col),
                ("LINEBEFORE", (0, 0), (0, -1), 4, sev_col),
                ("PADDING", (0, 0), (-1, -1), 8),
            ]))

            story.append(finding_box)
            story.append(Spacer(1, 10))

    # Build PDF
    doc.build(story, canvasmaker=NumberedCanvas)
    return output_path


# ───────────────────────────────────────────────────────────
# 2. Generate all_logs.pdf
# ───────────────────────────────────────────────────────────
def generate_logs_pdf(master_result: MasterScanResult, output_path: Path) -> Path:
    """Generates complete execution logs, probe trace telemetry, and failure diagnostics PDF.

    Includes A to Z audit trail:
      1. Target environment & runtime configuration
      2. Network probe delivery & HTTP status code distribution
      3. All 7 OWASP modules execution deep-dive & attack scenarios tested
      4. Probe diagnostics and error logs
      5. Full route-by-route execution trace (every probed endpoint)
      6. Cryptographic audit attestation and chain-of-custody fingerprint
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=54,
        bottomMargin=54,
    )

    styles = _get_pdf_styles()
    story = []

    # ── Title Banner ──
    story.append(Paragraph("SENTINELAPI AUDIT & EXECUTION LOGS", styles["title"]))
    timestamp_str = master_result.end_time or time.strftime("%Y-%m-%d %H:%M:%S UTC")
    story.append(Paragraph(f"Full Security Probe Trace, Telemetry & Network Diagnostics • Generated: {timestamp_str}", styles["subtitle"]))

    # ── Section 1: Executive Telemetry & Run Environment ──
    story.append(Paragraph("1. Target Environment & Execution Telemetry", styles["h1"]))

    planned = master_result.total_planned_probes
    succeeded = master_result.total_successful_probes
    failed = master_result.total_failed_probes
    health_pct = f"{(succeeded / planned * 100):.1f}%" if planned > 0 else "100.0%"

    st_col = _status_color(master_result.status)

    run_meta = [
        [
            Paragraph("<b>Target Host:</b>", styles["body"]),
            Paragraph(f"<code>{_esc(master_result.base_url)}</code>", styles["body"]),
            Paragraph("<b>Audit Status:</b>", styles["body"]),
            Paragraph(f"<font color='{st_col.hexval()}'><b>{master_result.status} (Exit Code: {master_result.exit_code})</b></font>", styles["body"]),
        ],
        [
            Paragraph("<b>Target API Name:</b>", styles["body"]),
            Paragraph(f"<b>{_esc(master_result.target_title)}</b>", styles["body"]),
            Paragraph("<b>OpenAPI Version:</b>", styles["body"]),
            Paragraph(f"v{_esc(master_result.spec_version)} ({master_result.total_endpoints} routes)", styles["body"]),
        ],
        [
            Paragraph("<b>Auth Strategy:</b>", styles["body"]),
            Paragraph(f"{_esc(master_result.auth_scheme or 'Unauthenticated')}", styles["body"]),
            Paragraph("<b>Probe Delivery Rate:</b>", styles["body"]),
            Paragraph(f"<font color='#059669'><b>{health_pct}</b></font> ({succeeded}/{planned} probes)", styles["body"]),
        ],
        [
            Paragraph("<b>Execution Window:</b>", styles["body"]),
            Paragraph(f"{_esc(master_result.start_time)} → {_esc(master_result.end_time)}", styles["body"]),
            Paragraph("<b>Failed Probes:</b>", styles["body"]),
            Paragraph(f"<font color='{'#dc2626' if failed > 0 else '#059669'}'><b>{failed} drops</b></font>", styles["body"]),
        ],
    ]
    meta_table = Table(run_meta, colWidths=[110, 160, 110, 124])
    meta_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
            ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#cbd5e1")),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ])
    )
    story.append(meta_table)
    story.append(Spacer(1, 14))

    # ── Section 2: HTTP Status Code & Network Telemetry Distribution Matrix ──
    story.append(Paragraph("2. HTTP Response Status Code & Network Distribution", styles["h1"]))

    status_counts: Dict[str, int] = {}
    for mod_res in master_result.module_results.values():
        for f in mod_res.findings:
            c = str(f.status_code) if f.status_code else "None"
            status_counts[c] = status_counts.get(c, 0) + 1
        for pe in mod_res.probe_errors:
            c = str(pe.status_code) if pe.status_code and pe.status_code > 0 else "0 (Timeout/Drop)"
            status_counts[c] = status_counts.get(c, 0) + 1

    total_probes_counted = sum(status_counts.values()) or 1

    code_rows = [
        [
            Paragraph("<b>HTTP Status Code</b>", styles["bold_cell"]),
            Paragraph("<b>Classification & Security Meaning</b>", styles["bold_cell"]),
            Paragraph("<b>Probes Count</b>", styles["bold_cell"]),
            Paragraph("<b>Traffic %</b>", styles["bold_cell"]),
        ]
    ]

    code_descriptions = {
        "200": ("200 OK", "Successful request / route delivered data", "#059669"),
        "201": ("201 Created", "Resource created successfully", "#059669"),
        "204": ("204 No Content", "Action executed with empty response", "#059669"),
        "301": ("301 Moved Permanently", "Redirect to canonical HTTPS URL", "#2563eb"),
        "302": ("302 Found", "Temporary redirection", "#2563eb"),
        "400": ("400 Bad Request", "Schema validation rejected malformed request", "#475569"),
        "401": ("401 Unauthorized", "Authentication barrier actively enforced", "#2563eb"),
        "403": ("403 Forbidden", "Access control / authorization boundary enforced", "#2563eb"),
        "404": ("404 Not Found", "Target route non-existent or hardened", "#475569"),
        "405": ("405 Method Not Allowed", "HTTP verb blocked by server route configuration", "#475569"),
        "429": ("429 Too Many Requests", "Rate limit / concurrency throttle successfully triggered", "#059669"),
        "500": ("500 Internal Server Error", "Unhandled backend exception / crash during probe", "#dc2626"),
        "502": ("502 Bad Gateway", "Upstream gateway or proxy connection failure", "#dc2626"),
        "503": ("503 Service Unavailable", "Backend service overload or maintenance", "#dc2626"),
        "0 (Timeout/Drop)": ("0 Connection Drop", "Network timeout, socket reset, or DNS failure", "#991b1b"),
        "None": ("Headers / Metadata Audit", "Security header or cookie verification check", "#334155"),
    }

    for code_key, count in sorted(status_counts.items(), key=lambda x: str(x[0])):
        desc_info = code_descriptions.get(code_key, (f"HTTP {code_key}", "Live server response", "#334155"))
        pct_str = f"{(count / total_probes_counted * 100):.1f}%"
        badge_html = f"<font color='{desc_info[2]}'><b>{desc_info[0]}</b></font>"
        code_rows.append([
            Paragraph(badge_html, styles["table_cell"]),
            Paragraph(desc_info[1], styles["table_cell"]),
            Paragraph(str(count), styles["bold_cell"]),
            Paragraph(pct_str, styles["table_cell"]),
        ])

    code_table = Table(code_rows, colWidths=[120, 224, 80, 80])
    code_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e293b")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#cbd5e1")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("ALIGN", (2, 0), (-1, -1), "CENTER"),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ])
    )
    story.append(code_table)
    story.append(Spacer(1, 14))

    # ── Section 3: All 7 OWASP Modules Execution Deep-Dive ──
    story.append(Paragraph("3. OWASP Top 10 Module Execution Log & Attack Scenarios", styles["h1"]))

    exec_rows = [
        [
            Paragraph("<b>Module Name</b>", styles["bold_cell"]),
            Paragraph("<b>OWASP Category</b>", styles["bold_cell"]),
            Paragraph("<b>Planned</b>", styles["bold_cell"]),
            Paragraph("<b>OK</b>", styles["bold_cell"]),
            Paragraph("<b>Failed</b>", styles["bold_cell"]),
            Paragraph("<b>Duration</b>", styles["bold_cell"]),
            Paragraph("<b>Status</b>", styles["bold_cell"]),
        ]
    ]

    for mod_id, mod_res in master_result.module_results.items():
        st = mod_res.status
        col = _status_color(st)
        dur_str = f"{mod_res.duration_seconds:.1f}s" if mod_res.duration_seconds > 0 else "< 1s"
        exec_rows.append([
            Paragraph(f"<b>{_esc(mod_res.scanner_name)}</b>", styles["table_cell"]),
            Paragraph(_esc(mod_res.owasp_category), styles["table_cell"]),
            Paragraph(str(mod_res.planned_probes), styles["table_cell"]),
            Paragraph(str(mod_res.successful_probes), styles["table_cell"]),
            Paragraph(str(mod_res.failed_probes), styles["table_cell"]),
            Paragraph(dur_str, styles["table_cell"]),
            Paragraph(f"<font color='{col.hexval()}'><b>{st}</b></font>", styles["bold_cell"]),
        ])

    exec_table = Table(exec_rows, colWidths=[150, 134, 44, 44, 44, 44, 44])
    exec_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f172a")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#cbd5e1")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("ALIGN", (2, 0), (-1, -1), "CENTER"),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ])
    )
    story.append(exec_table)
    story.append(Spacer(1, 10))

    # Attack Scenarios Narrative Summary Box
    scenarios_text = (
        "<b>Attack Scenarios & Verification Methods Tested Across All 7 Modules:</b><br/>"
        "• <b>BOLA / IDOR (API1:2023):</b> Tested horizontal privilege boundary tampering across entity IDs (id, user_id, booking_id). Simulated cross-tenant read/write mutations.<br/>"
        "• <b>Broken Authentication (API2:2023):</b> Probed JWT signature verification (alg: none, stripped headers), expired tokens, invalid claims, and unauthenticated endpoint access.<br/>"
        "• <b>Excessive Data Exposure (API3:2023):</b> Audited response payloads for leaked PII, unmasked credentials, password hashes, payment tokens, and internal database keys.<br/>"
        "• <b>Rate Limiting (API4:2023):</b> Dispatched concurrent rapid-fire request bursts (10–30 req/route) to verify HTTP 429 rate limit thresholds and anti-bruteforce safeguards.<br/>"
        "• <b>BFLA & Privilege Escalation (API5:2023):</b> Tested vertical access control by dispatching administrative methods (DELETE, PUT, POST) on sensitive /admin and /walker routes.<br/>"
        "• <b>Security Misconfiguration (API8:2023):</b> Audited HTTP response security headers (HSTS, CSP, X-Frame-Options, X-Content-Type-Options) and cookie security flags (HttpOnly, Secure, SameSite).<br/>"
        "• <b>Shadow & Zombie APIs (API9:2023):</b> Heuristic discovery against legacy /v1, /v2, /beta, /debug, and forgotten staging routes."
    )
    scenarios_box = Table([[Paragraph(scenarios_text, styles["small_body"])]], colWidths=[504])
    scenarios_box.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f1f5f9")),
        ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#cbd5e1")),
        ("PADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(scenarios_box)
    story.append(Spacer(1, 14))

    # ── Section 4: Probe Error & Network Failure Diagnostics ──
    all_probe_errors = master_result.all_probe_errors
    story.append(Paragraph(f"4. Probe Error & Network Failure Diagnostics ({len(all_probe_errors)} Events)", styles["h1"]))

    if not all_probe_errors:
        err_box = Table([[Paragraph("<font color='#059669'><b>✔ Zero Probe Failures Recorded (100% Network Integrity)</b><br/>All HTTP connections, SSL/TLS handshakes, and route verifications completed with zero packet drops, zero socket resets, and zero connection timeouts.</font>", styles["body"])]], colWidths=[504])
        err_box.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#ecfdf5")),
            ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#059669")),
            ("PADDING", (0, 0), (-1, -1), 9),
        ]))
        story.append(err_box)
    else:
        err_rows = [
            [
                Paragraph("<b>#</b>", styles["bold_cell"]),
                Paragraph("<b>Endpoint / Target</b>", styles["bold_cell"]),
                Paragraph("<b>Method</b>", styles["bold_cell"]),
                Paragraph("<b>Code</b>", styles["bold_cell"]),
                Paragraph("<b>Diagnostic Error & Security Impact</b>", styles["bold_cell"]),
            ]
        ]
        for idx, pe in enumerate(all_probe_errors, 1):
            err_rows.append([
                Paragraph(str(idx), styles["table_cell"]),
                Paragraph(f"<code>{_esc(pe.endpoint)}</code>", styles["mono_cell"]),
                Paragraph(_esc(pe.method), styles["bold_cell"]),
                Paragraph(str(pe.status_code), styles["table_cell"]),
                Paragraph(_esc(pe.error_message), styles["diag_cell"]),
            ])

        err_table = Table(err_rows, colWidths=[24, 170, 46, 40, 224])
        err_table.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#991b1b")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#f87171")),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.HexColor("#fff1f2"), colors.white]),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#fecdd3")),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ])
        )
        story.append(err_table)

    story.append(Spacer(1, 14))

    # ── Section 5: Complete Route-by-Route Probe Trace & Request Logs (A to Z Route Log) ──
    story.append(Paragraph("5. Complete Route-by-Route Probe Trace & Audit Logs", styles["h1"]))
    story.append(Paragraph("Chronological audit log of every individual endpoint, probe vector, response code, and diagnostic outcome evaluated during the security assessment.", styles["subtitle"]))

    trail_rows = [
        [
            Paragraph("<b>#</b>", styles["bold_cell"]),
            Paragraph("<b>Module</b>", styles["bold_cell"]),
            Paragraph("<b>Method</b>", styles["bold_cell"]),
            Paragraph("<b>Endpoint Path</b>", styles["bold_cell"]),
            Paragraph("<b>Code</b>", styles["bold_cell"]),
            Paragraph("<b>Outcome</b>", styles["bold_cell"]),
            Paragraph("<b>Diagnostic Reason / Audit Note</b>", styles["bold_cell"]),
        ]
    ]

    seq = 1
    for mod_id, mod_res in master_result.module_results.items():
        for f in mod_res.findings:
            res_str = "<font color='#dc2626'><b>VULN</b></font>" if f.is_vulnerable else "<font color='#059669'>PASS</font>"
            note = f.evidence or f.description or "Audit check verified"
            if len(note) > 130:
                note = note[:127] + "..."

            trail_rows.append([
                Paragraph(str(seq), styles["table_cell"]),
                Paragraph(_esc(mod_res.scanner_id), styles["table_cell"]),
                Paragraph(_esc(f.method), styles["bold_cell"]),
                Paragraph(f"<code>{_esc(f.endpoint)}</code>", styles["mono_cell"]),
                Paragraph(str(f.status_code or "-"), styles["table_cell"]),
                Paragraph(res_str, styles["table_cell"]),
                Paragraph(_esc(note), styles["diag_cell"]),
            ])
            seq += 1

    # Include probe errors in the full trace if any
    for pe in master_result.all_probe_errors:
        trail_rows.append([
            Paragraph(str(seq), styles["table_cell"]),
            Paragraph("network_probe", styles["table_cell"]),
            Paragraph(_esc(pe.method), styles["bold_cell"]),
            Paragraph(f"<code>{_esc(pe.endpoint)}</code>", styles["mono_cell"]),
            Paragraph(str(pe.status_code or "0"), styles["table_cell"]),
            Paragraph("<font color='#991b1b'><b>ERROR</b></font>", styles["table_cell"]),
            Paragraph(_esc(pe.error_message), styles["diag_cell"]),
        ])
        seq += 1

    trail_table = Table(trail_rows, colWidths=[24, 76, 44, 150, 36, 46, 128], repeatRows=1)
    trail_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f172a")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#cbd5e1")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("ALIGN", (0, 0), (0, -1), "CENTER"),
            ("ALIGN", (2, 0), (2, -1), "CENTER"),
            ("ALIGN", (4, 0), (5, -1), "CENTER"),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ])
    )
    story.append(trail_table)
    story.append(Spacer(1, 16))

    # ── Section 6: Cryptographic Audit Attestation & Chain of Custody ──
    story.append(Paragraph("6. Audit Attestation & Chain of Custody", styles["h1"]))

    run_raw_data = f"{master_result.target_title}|{master_result.base_url}|{master_result.start_time}|{master_result.status}"
    run_hash = hashlib.sha256(run_raw_data.encode("utf-8")).hexdigest()

    attestation_text = (
        f"<b>Audit Run Fingerprint (SHA-256):</b> <code>{run_hash}</code><br/>"
        f"<b>Assessment Engine:</b> SentinelAPI Core v1.0.0 (Fail-Closed Automated Security Scanner)<br/>"
        f"<b>Target Base URL:</b> <code>{_esc(master_result.base_url)}</code> • <b>Status:</b> <b>{master_result.status}</b><br/>"
        "<b>Fail-Closed Policy Attestation:</b> This security report was produced under strict fail-closed criteria. "
        "Every endpoint probe was verified via live HTTP request handshakes. Zero false passes were permitted for unreachable or unverified services."
    )
    attest_box = Table([[Paragraph(attestation_text, styles["small_body"])]], colWidths=[504])
    attest_box.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
        ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#94a3b8")),
        ("PADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(attest_box)

    # Build PDF
    doc.build(story, canvasmaker=NumberedCanvas)
    return output_path


def generate_scan_pdfs(master_result: MasterScanResult, output_dir: Path) -> tuple[Path, Path]:
    """Generates both vulnerabilities.pdf and all_logs.pdf in the specified output directory.

    Returns:
        tuple[Path, Path]: (vulnerabilities_pdf_path, all_logs_pdf_path)
    """
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    vuln_path = out_dir / "vulnerabilities.pdf"
    logs_path = out_dir / "all_logs.pdf"
    generate_vulnerabilities_pdf(master_result, vuln_path)
    generate_logs_pdf(master_result, logs_path)
    return vuln_path, logs_path
